name: quay Users Server Workflow

on:
  workflow_dispatch:
  push:
    branches: [ "deployment" ]
    paths:
      - 'Users/Server/**'

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: users-server
        tags: latest ${{ github.sha }}
        context: ./Users/Server
        dockerfiles: |
          ./Users/Server/Dockerfile
    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/mervegunak
        username: mervegunak
        password: ${{ secrets.QUAY_IMAGE_REGISTRY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
